INSERT INTO questions (quiz_id, question_number, question_text, correct_answer, question_option_a, question_option_b, question_option_c, question_option_d)
VALUES
(1, 1, 'What is the capital of Alberta?', 'a', 'Edmonton', 'Calgary', 'Leduc', 'Red Deer'),
(1, 2, 'What is the capital of British Columbia?', 'd', 'Vancouver', 'Burnaby', 'Dawson Creek', 'Victoria'),
(1, 3, 'What is the capital of Manitoba?', 'b', 'Flin Flon', 'Winnipeg', 'Thompson', 'Winkler'),
(1, 4, 'What is the capital of New Brunswick?', 'c', 'Bathhurst', 'Moncton', 'Fredericton', 'Saint John'),
(1, 5, 'What is the capital of Newfoundland and Labrador?', 'c', 'Labrador', 'Corner Brook', 'Saint John''s', 'Mount Pearl'),
(1, 6, 'What is the capital of Nova Scotia?', 'd', 'Dartmouth', 'Dryden', 'Sydney', 'Halifax'),
(1, 7, 'What is the capital of Ontario?', 'a', 'Toronto', 'Cornwall', 'Ottawa', 'North Bay'),
(1, 8, 'What is the capital of Prince Edward Island?', 'b', 'Pembroke', 'Charlottetown', 'Stratford', 'Eastern Township'),
(1, 9, 'What is the capital of Quebec?', 'a', 'Quebec', 'Laval', 'Montreal', 'Sault Ste. Marie'),
(1, 10, 'What is the capital of Saskatchewan?', 'c', 'Saskatoon', 'Prince Albert', 'Regina', 'Swift Current'),
(1, 11, 'What is the capital of the Yukon?', 'd', 'Moose Jaw', 'Regina', 'Weyburn', 'Whitehorse'),
(1, 12, 'What is the capital of Nunavut?', 'a', 'Iqaluit', 'Grise Fiord', 'Iglooik', 'Qikiqtarjuaq'),
(1, 13, 'What is the capital of the Northwest Territories?', 'b', 'Aklavik', 'Yellowknife', 'Inuvik', 'Sachs Harbour'),
(2, 1, '3 * 50 + 27 ', 'a', '177', '170', '277', '53'),
(2, 2, '2^5', 'b', '30', '32', '64', '25'),
(2, 3, '8 * 8 - 9 + 67', 'c', '124', '136', '122', '15'),
(2, 4, '5/15 + 10/15 - 15/15', 'c', '5', '10', '0', '-16'),
(2, 5, '(6 * 57)^2 - 17', 'c', '12345', '112345', '1996947', '19969470'),
(2, 6, '9 * 0', 'a', '0', '9', '09', '15'),
(2, 7, '5 + 2 + 3', 'a', '10', '12', '100', '0'),
(2, 8, '1/10000', 'd', '0.01', '0.001', '0.001', '0.0001'),
(2, 9, '(12 * 12) / 12', 'd', '122', '124', '2', '12'),
(2, 10, '8 * (9 + 12) - (3 + 5) * 26', 'd', '40', '400', '-4', '-40'),
(3, 1, 'You should always mix salt and yeast together before adding it to a mix to made bread dough. The salt feeds the yeast and makes the finished product rise better.', 'b', 'true', 'false', '', ''),
(3, 2, 'A poolish is a mix of water, flour and yeast.  It is used in the production of a number of French bread products.', 'a', 'true', 'false', '', ''),
(3, 3, 'A sourdough starter is used to flavour and leaven sourdough.  Once made, it should sit at room temperature indefinitely until it is needed and only needs to be “fed” once a month.', 'b', 'true', 'false', '', ''),
(3, 4, 'If you forget to put yeast in your bread it can be salvaged - just let it proof longer.  The natural bacteria and wild yeast in the air will eventually make it rise.', 'b', 'true', 'false', '', ''),
(3, 5, 'If your bread comes out very pale and bland, the dough may have been missing salt.', 'a', 'true', 'false', '', ''),
(3, 6, 'In a production bakery, the ideal humidity level for a proofer is 100%.', 'b', 'true', 'false', '', ''),
(3, 7, 'White flour is naturally gluten free as it doesn''t contain the wheat germ or bran.', 'b', 'true', 'false', '', ''),
(3, 8, 'Bread dough cannot be over-mixed.  The longer you mix it, the more gluten development there will be resulting in a tastier, chewier product.', 'b', 'true', 'false', '', ''),
(3, 9, 'Whole grain flour contains more gluten than refined white flour?', 'b', 'true', 'false', '', ''),
(3, 10, 'It was once believed that cutting a cross on the top of your soda bread would let the devil escape from the loaf while it baked.', 'a', 'true', 'false', '', ''),
(4, 1, 'The technical name For Brewer''s Yeast is saccharomyces.', 'a', 'true', 'false', '', ''),
(4, 2, 'Guinness is the oldest brewery in the world.', 'b', 'true', 'false', '', ''),
(4, 3, 'Wort is the liquid extracted from the mashing process during the brewing of beer.', 'a', 'true', 'false', '', ''),
(4, 4, 'IPA stands for International Pale Ale.', 'b', 'true', 'false', '', ''),
(4, 5, 'Hops are a great, nutritious treat for dogs.', 'b', 'true', 'false', '', ''),
(4, 6, 'The German word Hefe means yeast.', 'a', 'true', 'false', '', ''),
(4, 7, 'Cenosillicaphobia is the fear of an empty glass.', 'a', 'true', 'false', '', ''),
(4, 8, 'Craft Beer contains high levels of silicon, which can weaken your bones.', 'b', 'true', 'false', '', ''),
(4, 9, 'There exist ancient Egyptian texts that contain over 100 medicinal uses for beer.', 'a', 'true', 'false', '', ''),
(4, 10, 'In medieval Europe, the average person drank 220-250 litres of beer a year, as it was cleaner and safer to drink than the water.', 'a', 'true', 'false', '', ''),
(4, 11, 'Beer is fat free.', 'a', 'true', 'false', '', ''),
(4, 12, 'The strongest beer in the world is called “Snake Venom” and was created by the Scottish brewery Brewmeister.  It has a strength of 67.5%.', 'a', 'true', 'false', '', ''),
(4, 13, 'Hops act as a preservative and will help keep beer fresher for longer.', 'a', 'true', 'false', '', ''),
(5, 1, 'Who became the UFC''s youngest ever champion?', 'a', 'Jon Jones', 'Conor Mcgregor', 'Jose Aldo', 'Nate Diaz'),
(5, 2, 'Who was the longest reigning UFC champion?', 'c', 'Jon Jones', 'Jose Aldo', 'Anderson Silva', 'Conor Mcgregor'),
(5, 3, 'Who won the first ever UFC tournament at UFC 1?', 'b', 'Ken Shamrock', 'Royce Gracie', 'Dan Severn', 'Conor Mcgregor'),
(5, 4, 'What UFC event had the largest number of PPV buys?', 'd', 'UFC 202: Diaz vs Mcgregor II', 'UFC 100: Lesnar vs. Mir II', 'UFC 196: McGregor vs. Diaz', 'UFC 229: Nurmagomedov vs Mcgregor'),
(5, 5, 'Who was the first Canadian to ever become a UFC champion', 'a', 'Carlos Newton', 'George St Pierre', 'Rory Mcdonald', 'Conor Mcgregor'),
(5, 6, 'Who was UFC''s first ever champion to hold the title in two different weight classes?', 'd', 'BJ Penn', 'George St Pierre', 'Daniel Cormier', 'Conor Mcgregor'),
(6, 1, 'Francis mentions the word "potato" an average of 2 times per LHL lecture.', 'b', 'true', 'false', '', ''),
(6, 2, 'The US Department of Agriculture has stated that “a diet of whole milk and potatoes would supply almost all of the food elements necessary for the maintenance of the human body".', 'a', 'true', 'false', '', ''),
(6, 3, 'The potato is about 60% water and 40% solids.', 'b', 'true', 'false', '', ''),
(6, 4, 'The average American eats about 124 pounds of potatoes per year while Germans eat about twice as much.', 'a', 'true', 'false', '', ''),
(6, 5, 'Edgar Allen Poe makes multiple mentions of potatoes in his famously dark poetry, including the excerpt: "Mid dark thoughts of the gray tombstone— Buried in the dark earth amongst potatoes."', 'b', 'true', 'false', '', ''),
(6, 6, 'Potato blossoms used to be a hit in royal fashion. Potatoes became fashionable when Marie Antoinette walked through the French countryside wearing potato blossoms in her hair.', 'a', 'true', 'false', '', ''),
(6, 7, 'Sweet potatoes are in the same family as white potatoes.', 'b', 'true', 'false', '', ''),
(6, 8, 'Canada produces approximately $500M worth of potatoes annually.', 'b', 'true', 'false', '', ''),
(6, 9, 'Potatoes originally come from Ireland.', 'b', 'true', 'false', '', ''),
(6, 10, 'The potato was the first vegetable to be grown in space.', 'a', 'true', 'false', '', ''),
(6, 11, 'The potato skin contains a high level of its nutrients, about 17 % of a its total zinc, 34% of its calcium and 55% of its iron.', 'a', 'true', 'false', '', '');
