INSERT INTO questions (quiz_id, question_number, question_text, correct_answer, question_option_a, question_option_b, question_option_c, question_option_d)
VALUES
(1, 1, 'What is the capital of Alberta?', 'a', 'Edmonton', 'Calgary', 'Leduc', 'Red Deer'),
(1, 2, 'What is the capital of British Columbia?', 'd', 'Vancouver', 'Burnaby', 'Dawson Creek', 'Victoria'),
(1, 3, 'What is the capital of Manitoba?', 'b', 'Flin Flon', 'Winnipeg', 'Thompson', 'Winkler'),
(1, 4, 'What is the capital of New Brunswick?', 'c', 'Bathhurst', 'Moncton', 'Fredericton', 'Saint John'),
(1, 5, 'What is the capital of Newfoundland and Labrador?', 'c', 'Labrador', 'Corner Brook', 'Saint John''s', 'Mount Pearl'),
(1, 6, 'What is the capital of Nova Scotia?', 'd', 'Dartmouth', 'Dryden', 'Sydney', 'Halifax'),
(1, 7, 'What is the capital of Ontario?', 'a', 'Toronto', 'Cornwall', 'Ottawa', 'North Bay'),
(1, 8, 'What is the capital of Prince Edward Island?', 'b', 'Pembroke', 'Charlottetown', 'Stratford', 'Eastern Township'),
(1, 9, 'What is the capital of Quebec?', 'a', 'Quebec', 'Laval', 'Montreal', 'Sault Ste. Marie'),
(1, 10, 'What is the capital of Saskatchewan?', 'c', 'Saskatoon', 'Prince Albert', 'Regina', 'Swift Current'),
(1, 11, 'What is the capital of the Yukon?', 'd', 'Moose Jaw', 'Regina', 'Weyburn', 'Whitehorse'),
(1, 12, 'What is the capital of Nunavut?', 'a', 'Iqaluit', 'Grise Fiord', 'Iglooik', 'Qikiqtarjuaq'),
(1, 13, 'What is the capital of the Northwest Territories?', 'b', 'Aklavik', 'Yellowknife', 'Inuvik', 'Sachs Harbour'),
(2, 1, '3 * 50 + 27 ', 'a', '177', '170', '277', '53'),
(2, 2, '2^5', 'b', '30', '32', '64', '25'),
(2, 3, '8 * 8 - 9 + 67', 'c', '124', '136', '122', '15'),
(2, 4, '5/15 + 10/15 - 15/15', 'c', '5', '10', '0', '-16'),
(2, 5, '(6 * 57)^2 - 17', 'c', '12345', '112345', '1996947', '19969470'),
(2, 6, '9 * 0', 'a', '0', '9', '09', '15'),
(2, 7, '5 + 2 + 3', 'a', '10', '12', '100', '0'),
(2, 8, '1/10000', 'd', '0.01', '0.001', '0.001', '0.0001'),
(2, 9, '(12 * 12) / 12', 'd', '122', '124', '2', '12'),
(2, 10, '8 * (9 + 12) - (3 + 5) * 26', 'd', '40', '400', '-4', '-40'),
(3, 1, 'You should always mix salt and yeast together before adding it to a mix to made bread dough. The salt feeds the yeast and makes the finished product rise better.', 'b', 'true', 'false', '', ''),
(3, 2, 'A poolish is a mix of water, flour and yeast.  It is used in the production of a number of French bread products.', 'a', 'true', 'false', '', ''),
(3, 3, 'A sourdough starter is used to flavour and leaven sourdough.  Once made, it should sit at room temperature indefinitely until it is needed and only needs to be “fed” once a month.', 'b', 'true', 'false', '', ''),
(3, 4, 'If you forget to put yeast in your bread it can be salvaged - just let it proof longer.  The natural bacteria and wild yeast in the air will eventually make it rise.', 'b', 'true', 'false', '', ''),
(3, 5, 'If your bread comes out very pale and bland, the dough may have been missing salt.', 'a', 'true', 'false', '', ''),
(3, 6, 'In a production bakery, the ideal humidity level for a proofer is 100%.', 'b', 'true', 'false', '', ''),
(3, 7, 'White flour is naturally gluten free as it doesn''t contain the wheat germ or bran.', 'b', 'true', 'false', '', ''),
(3, 8, 'Bread dough cannot be over-mixed.  The longer you mix it, the more gluten development there will be resulting in a tastier, chewier product.', 'b', 'true', 'false', '', ''),
(3, 9, 'Whole grain flour contains more gluten than refined white flour?', 'b', 'true', 'false', '', ''),
(3, 10, 'It was once believed that cutting a cross on the top of your soda bread would let the devil escape from the loaf while it baked.', 'a', 'true', 'false', '', ''),
(4, 1, 'The technical name For Brewer''s Yeast is saccharomyces.', 'a', 'true', 'false', '', ''),
(4, 2, 'Guinness is the oldest brewery in the world.', 'b', 'true', 'false', '', ''),
(4, 3, 'Wort is the liquid extracted from the mashing process during the brewing of beer.', 'b', 'true', 'false', '', ''),
(4, 4, 'IPA stands for International Pale Ale.', 'b', 'true', 'false', '', ''),
(4, 5, 'Hops are a great, nutritious treat for dogs.', 'b', 'true', 'false', '', ''),
(4, 6, 'The German word Hefe means yeast.', 'a', 'true', 'false', '', ''),
(4, 7, 'Cenosillicaphobia is the fear of an empty glass.', 'a', 'true', 'false', '', ''),
(4, 8, 'Craft Beer contains high levels of silicon, which can weaken your bones.', 'b', 'true', 'false', '', ''),
(4, 9, 'There exist ancient Egyptian texts that contain over 100 medicinal uses for beer.', 'a', 'true', 'false', '', ''),
(4, 10, 'In medieval Europe, the average person drank 220-250 litres of beer a year, as it was cleaner and safer to drink than the water.', 'a', 'true', 'false', '', ''),
(4, 11, 'Beer is fat free.', 'a', 'true', 'false', '', ''),
(4, 12, 'The strongest beer in the world is called “Snake Venom” and was created by the Scottish brewery Brewmeister.  It has a strength of 67.5%.', 'a', 'true', 'false', '', ''),
(4, 13, 'Hops act as a preservative and will help keep beer fresher for longer.', 'a', 'true', 'false', '', '');
